package config

import (
	"os"
	"testing"
)

func TestGetJWTSecret_AutoGenerated(t *testing.T) {
	secret := GetJWTSecret()
	if len(secret) < 32 {
		t.Fatalf("Expected secret to have at least 32 characters, got len %d: %s", len(secret), secret)
	}

	secret2 := GetJWTSecret()
	if secret != secret2 {
		t.Fatalf("Expected secret to be cached, got %s and %s", secret, secret2)
	}

	refreshSecret := GetJWTRefreshSecret()
	if len(refreshSecret) < 32 {
		t.Fatalf("Expected refresh secret to have at least 32 characters, got len %d", len(refreshSecret))
	}
}

func TestGetOrGenerateSecret_EnvPrecedence(t *testing.T) {
	customKey := "TEST_CUSTOM_JWT_SECRET"
	expectedVal := "test-secret-val-custom-env-precedence-check"
	_ = os.Setenv(customKey, expectedVal)
	defer os.Unsetenv(customKey)

	val := getOrGenerateSecret(customKey, ".test_secret_file")
	if val != expectedVal {
		t.Fatalf("Expected value from environment, got %s", val)
	}
}

func TestValidateSecretStrength(t *testing.T) {
	if err := validateSecretStrength("JWT_SECRET", "short"); err == nil {
		t.Fatalf("Expected rejection of secrets shorter than 32 characters")
	}
	if err := validateSecretStrength("JWT_SECRET", ""); err == nil {
		t.Fatalf("Expected rejection of empty secrets")
	}
	longSecret := ""
	for i := 0; i < 32; i++ {
		longSecret += "a"
	}
	if err := validateSecretStrength("JWT_SECRET", longSecret); err != nil {
		t.Fatalf("Expected 32-character secret to be accepted, got: %v", err)
	}
}
